evry_thing_login:
    resource: "@EvryThingLoginBundle/Resources/config/routing.yml"
    prefix:   /blog

evry_thing_blog:
    resource: "@EvryThingBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
